citas/urls.py
from django.urls import path, include

from . import views


app_name = 'citas'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('loger', views.LogeView.as_view(), name='logeador'),

    path('edicion', views.EdicionFormView.as_view(), name='edicion' ),

    path('edicion_2', views.EdicionFormView2.as_view(), name='edicion_2'),

    path('<review>', views.ResenaView.as_view(), name='resena'),

    

   
]

cyber/urls.py
from django.urls import path

from . import views


app_name = 'cyber'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

tienda/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls ),
    path('', include('cyber.urls') ),
    path('citas/', include('citas.urls') ),
]
# seccion habilita la el mapeo para urls de login y permisos de usuario
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

citas/models.py
from django.db import models
# Create your models here.

class Lugares(models.Model):
	Sujeto = models.CharField(max_length=50)
	

	def __str__(self):
		return self.Sujeto
    

class Critica_sitios(models.Model):
	opinion =models.CharField(max_length=400)
	calificacion = models.IntegerField(default=0)

	MASCULINO='Axel E González'
	FEMENINO= 'Bianca E Monroy'
	Type_CHOICES =(
		(MASCULINO, 'Axel E González'),
		(FEMENINO, 'Bianca E Monroy')
		)

	evaluador= models.CharField(choices=Type_CHOICES, default= FEMENINO, max_length=20)

	ya_visitado=models.BooleanField(default=False)
	
	lugar = models.ForeignKey(Lugares, on_delete=models.CASCADE)


	def __str__(self):

		return self.opinion

cyber/models.py
from django.db import models

# Create your models here.

citas/forms.py
from django import forms

from .models import  Lugares, Critica_sitios

class PostForm(forms.ModelForm):

    class Meta:
        model = Lugares
       	fields = ('Sujeto',)


class CitasForm(forms.ModelForm):
	class Meta:
		model = Critica_sitios
		fields = ('opinion', 'calificacion','evaluador', 'ya_visitado', 'lugar')
			

citas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic, View
from citas.models import Lugares, Critica_sitios
#from django.core.urlresolvers import reverse
from django.views.generic import ListView
from .forms import PostForm, CitasForm
from django.views.generic.edit import FormView

#login
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexView(generic.ListView):

    template_name = 'citas/index.html'
    context_object_name = 'vista_productos'
    model = Critica_sitios


    def get_context_data(self, **kwargs):
        #No visitado segmento
        context = super(IndexView, self).get_context_data(**kwargs)

        a= Critica_sitios.objects.filter(ya_visitado="False")
        context['titulos'] = a
        c=0
        for a in context['titulos']:
            if c == 0:
                segundo=[a.lugar]
                c=c+1
            else:
                if a.lugar not in segundo:
                    segundo.append(a.lugar)
        
        context['titulos_lugar']=segundo
        #ya visitado

        a1 =Critica_sitios.objects.filter(ya_visitado="True")
        context['titulos2']=a1
        d=0
        for c1 in context['titulos2']:

            if d==0:

                segundo2=[c1.lugar]
                
                d=d+1
            else:
                if  c1.lugar not in segundo2:
                    segundo2.append(c1.lugar)
        cont1=0
        for repetido in context['titulos_lugar']:
            try:
                filtro_f=segundo2.index(repetido)
                segundo2.pop(filtro_f)
            except:
                pass

        try:
            context['titulos_lugar2']=segundo2
            
        except:
            context['titulos_lugar2']="Sin elementos"



        

        return context


        




    def get_queryset(self):
        """DEFINE LISTA DE CONSULTAS"""
        #informacion =Critica_sitios.objects.filter(ya_visitado="True")
        pass
        


        

    
class BaseView(generic.ListView):
    template_name = 'citas/base.html'
    context_object_name = 'vista_productos'
    def get_queryset(self):
        """DEFINE LISTA DE CONSULTAS"""
        pass







class ResenaView(generic.ListView):
    template_name = 'citas/Resena.html'
    context_object_name = 'vista_productos'
    model=Lugares

    def get_context_data(self, **kwargs):

        context = super(ResenaView, self).get_context_data(**kwargs)

        self.filtrado=Lugares.objects.filter(pk = self.kwargs['review'])#filtro de objetos con pk dinamico
       
        self.contenido_lugar =Critica_sitios.objects.filter(lugar= self.kwargs['review'])

        context['contenido_l']=self.contenido_lugar

        context['prueba']=self.filtrado
        suma = 0
        contador=0
        for a in self.contenido_lugar:
            contador = contador + 1
            suma = suma + a.calificacion



        context['final']= suma/contador
       
              
        return context  






class EdicionFormView(LoginRequiredMixin, FormView):
    
    form_class = PostForm
    initial = {'key': 'value'}
    template_name = 'citas/Edicion.html'
    

    def get(self, request, *args, **kwargs):
        form= self.form_class(initial=self.initial)

       
        return render(request, self.template_name, {'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        
        if form.is_valid():
           

           post=form.save()
           

           return HttpResponseRedirect('/citas/edicion_2')

        return render(request, self.template_name, {'form': form})
           
           
            #debo aprender a realizar negociaciones


class EdicionFormView2(LoginRequiredMixin, FormView):
    form_class=CitasForm
    initial={'key':'value'}
    template_name= 'citas/Edicion2.html'
    def get(self, request, *args, **kwargs):
        form = self.form_class(initial = self.initial)
        return render(request, self.template_name, {'form':form})

    def post(self, request, *args, **kwars):
        form = self.form_class(request.POST)
        if form.is_valid():

            post = form.save()

            return HttpResponseRedirect('/citas')

        return render(request, self.template_name, {'form':form})


class EditFormView(FormView):
    pass




class LogeView(generic.ListView):
    """docstring for LogView"""
    template_name = 'citas/login.html'
    context_object_name = 'vista_productos'
    def get_queryset(self):
        pass




"""
class EdicionFormView(FormView):
    
    form_class = PostForm
    initial = {'key': 'value'}
    template_name = 'citas/Edicion.html'
    success_url = 'citas:resena'

    def get(self, request, *args, **kwargs):
        form= self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        def form_valid(self, form):
           
            form=post.save()
            return super().form_valid(form)
            #debo aprender a realizar negociaciones
"""        

cyber/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic




class IndexView(generic.ListView):
    template_name = 'cyber/index.html'
    context_object_name = 'vista_productos'

    def get_context_data(self, **kwargs):


        context = super(IndexView, self).get_context_data(**kwargs)

        context['some_data'] = 'NUESTRA UBICACIÓN'
        return context


    def get_queryset(self):
        """Return the last five published questions."""
        pass

citas/templates/citas/Edicion.html
{% extends 'citas/base.html' %}

{% block content %}

<script type="text/javascript">

  window.alert(' ¡Por cierto, mi amor Bianquita felicidades por tú empleo. Yo se que eres la mejor :D! ');
</script>
    <h3 class="text-center">Agrega un Nuevo lugar</h3>

    <form  action=" {% url 'citas:edicion' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="AGREGA UN NUEVO LUGAR">
	</form>

	


{% endblock %}

citas/templates/citas/Edicion2.html
{% extends 'citas/base.html' %}

{% block content %}
    <h3 class="text-center">Agrega una reseña de lugar</h3>

    <form  action=" {% url 'citas:edicion_2' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Listo">
</form>


<script type="text/javascript">
	const input = document.querySelector();
	input.setAttribute('type', 'textarea');
</script>

{% endblock %}

citas/templates/citas/Resena.html
	{% extends 'citas/base.html' %}

	{% block content %}

	{{ user }}
	{%for p in prueba%}

	<h1 class="text-center">{{p}}</h1>
	{%endfor%}
	<div class="row">

		
		<div class ="col-lg-12 col-md-12 col-sm-12 col-xs-12">	

			{%for a in contenido_l%}
			<div  id="vineta">
			<h3 class="text-center">LUGAR EVALUADO POR :</h3>

			<h4 class="text-center">{{a.evaluador}}</h4>

			<h4 class="text-center">{{a.calificacion}}</h4>	
				
			
				
			</div>

			<div id="vineta2">
				<h3>RESEÑA DE CONTENIDO : </h3>

				<h4 class="text-center">{{a.opinion}}</h4>
				
			</div>

			{%endfor%}

			<!--
			{%for a in opiniones%}
		  		<div id = "titu"> 
		  			<h3 class="text-center">Evaluado por : {{a.evaluador}}</h3>
		  			<p>{{a.opinion}}</p>	
		  			<p class="text-right">Calificación individual:{{a.calificacion}}</p>

		  		 </div>
		  	{%endfor%}

		  -->
		
		</div>

		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		
		</div>

	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div id ="pie">
			<h1 class="text-center">Promedio de calificaciones</h1>
			<h2 class="text-center"> {{final}}</h2>


			<p class="text-right"><a href="{% url 'citas:index' %}">Regresa</a></p>


			</div>
		</div>

	</div>
		


    
{% endblock %}

citas/templates/citas/base.html
{% load static %}
<!DOCTYPE html>
 <html>
   <head>
    <title>LISTA DE CITAS</title>
    	
      <link rel="stylesheet" type="text/css" href="{% static 'citas/1.css' %}">

   
       <!--Sitio con la fuente-->
       <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet"> 
        <!--Sitio con la fuente-->

	     <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>  
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
     <link rel="stylesheet" type="text/css" href=" https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
   </head>

<body id ="cuerpo">

	<div class="container-fluid">

        
         
         
         {% block content %}

            

         
         {% endblock %}
  </div>
<style >
  h1,h2, h3, h4, h5, a{  
    font-family: 'Bebas Neue', cursive;
    color: black;
    font-weight: bolder;
}



</style>

<!--
<style>
	h1{  font-family: 'Bebas Neue', cursive;
}

    body {
  background-color: black;
  height: 100vh;

  align-items:center;
  justify-content: center;

  font-weight: bold;
  text-align: right;
	}

	/* Css - Texto con Degradado#031b27 */
	h1,h2, h3,h4, h5, h6, ul, li{
    animation: fluido 10s ease-in-out infinite;
  background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
  background-size: 300%;
  -webkit-background-clip: text;
          background-clip: text;
  -webkit-text-fill-color: transparent;
		}


	p{

  animation: fluido 10s ease-in-out infinite;
  background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
  background-size: 300%;
  -webkit-background-clip: text;
          background-clip: text;
  -webkit-text-fill-color: transparent;
	}

	@keyframes fluido {
    0% { background-position: 0 50% }
    50% { background-position: 100% 50% }
    100% { background-position: 0 50% }
					}
</style>

-->



</body>






</html>

citas/templates/citas/index.html
{% extends 'citas/base.html' %}

{% block content %}
	


    {% if user.is_authenticated %}
    	<div class="row">
    		<div class="col-lg-12 col-md-12 col-12 col-xs-12">
    			<a href="{%url 'logout'%}">cierra tu sesión</a>
    		</div>
    	</div> 
   	{% endif %} 



    <div class="row" >
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" >
			<h1 class="text-center" id = "titu">No visitados</h1>
			
    		{% for titulo in titulos_lugar %} 
    			<h4 class="text-center" id="seleccion">

    				<a href="{% url 'citas:resena' titulo.pk %}">{{ titulo }}</a>
    				
    			</h4>
    		{% endfor %}
		</div>


		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<h1 class="text-center" id = "titu">Ya visitados</h1>
			<div id="desenfoque">
    			{% for titulo1 in titulos_lugar2 %} 
    				<h4 class="text-center" id="seleccion">
    					<a href="{% url 'citas:resena' titulo1.pk %}">{{ titulo1 }}
    					</a></h4>
    			{% endfor %}
    		</div>
		</div>
	</div>



	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

			<h3 class="text-rigth">
				<a href="{% url 'citas:edicion' %}">Agregar entrada</a>
			</h3>


		<div>

	</div>


    


{% endblock %}

citas/templates/citas/login.html
{% extends 'citas/base.html' %}

{% block content %}
    <h3 class="text-center">Sitio para autenticar</h3>
{% endblock %}

cyber/templates/cyber/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

	<!-- fuente -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&family=Bebas+Neue&family=Dancing+Script&family=Shizuru&display=swap" rel="stylesheet"> 


	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> <!--este maldito le da la propiedad responsive :S -->

	<link rel="stylesheet" type="text/css" href="{% static 'cyber/styles2.css' %}">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">

	<!--Head block -->
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="header">

			<div id="logo"><img src= "{% static 'cyber/imagen/logo.png'%}" class="img-responsive" id="logo"></div>


		</div>
	</div>
	<!--Middle block-->	
	<div class="row">
		<div class="col-lg-12 col-sd-12 col-sm-12 col-xs-12 ">
			<!--Barra de busqueda -->
			<div id="BusquedaG">
						<center>
							<FORM method=GET action="http://www.google.com/search">
								<TABLE bgcolor="#fde0a2 "><tr><td>
								<A HREF="http://www.google.com/">
								<IMG SRC="{%static 'cyber/imagen/logoGoo.png'%}" border="0" ALT="Google" align="absmiddle"  height="80" >
								<!--<IMG SRC="https://www.trecebits.com/wp-content/uploads/2015/09/nuevo_logo_google.jpg" border="0" ALT="Google" align="absmiddle" width="130" height="90" > --> </A>
								<INPUT TYPE=text name=q size=31 maxlength=255 value="">
								<INPUT TYPE=hidden name=hl value=es>
								<INPUT type=submit name=btnG VALUE="Búsqueda Google" style="color:#1a889f;">
								</td></tr></TABLE>
							</FORM>
						</center>
				</div>
		</div>
	</div>
	<!--Primer fila -->
	<div class="row">

		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
			<div id="prueba1" class="prueba1">
				<br>
				<h2 class="text-center">FOTOCOPIAS</h2>
					
				<h3 class="text-center">COLOR</h3>
				
				<h4 class="text-center">7 pesos c/u</h4>
				<br>
				<h3 class="text-center">BLANCO Y NEGRO</h3>
				<H4 class="text-center">1 PESO CADA UNA</H4>
			</div>
		</div>


		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
			<div id="prueba1">
				<br>
				<h2 class="text-center">IMPRESIÓN</h2>
					
				<h3 class="text-center">COLOR</h3>
				
				<h4 class="text-center">7 pesos c/u</h4>
				<br>
				<h3 class="text-center">BLANCO Y NEGRO</h3>
				<H4 class="text-center">1 PESO CADA UNA</H4>
			</div>
		</div>


		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
			<div id="prueba1">
				<br>
				<h3 class="text-center">REPARACIONES</h3>
					
				<h3 class="text-center">EQUIPOS DE COMPUTO</h3>
				<br>
				<h4 class="text-center">PROGRAMAS</h4>

				<H4 class="text-center">FORMATEOS</H4>
			</div>
		</div>

	</div>

	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
			<a href="https://www.ilovepdf.com/es">
				<div id="prueba1" class="prueba1">
				<br>
				<h3 class="text-center">HERRAMIENTA PARA PDF</h3>
				<div><img src="{% static 'cyber/imagen/ilovepdf.png'%}" class="img-responsive"></div>
			</div>
			</a>
		</div>

		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
			
			<div id ="prueba1">
				<br>
				<h3 class="text-center">DISEÑO DE PAGINAS WEB</h3>
				<br>
				<h3 class="text-center">Y</h3>
				<br>
				<H3 class="text-center">BLOG DE DIVULGACIÓN</H3>
			</div>

		</div>

		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
			<div id="prueba1">
				<br>

				<h3 class="text-center">{{some_data}}</h3>

				<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1881.9394855057676!2d-98.93838416210473!3d19.374392518457604!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses-419!2smx!4v1645051439216!5m2!1ses-419!2smx" width="200" height="200" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
			</div>
			<br>
		</div>


		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="pie">
				
				


			</div>
		</div>


		
		
	</div>























    <script type="text/javascript">
    	var index = 0;

    	var listaimg = ["{% static 'cyber/imagen/fondo2.jpg' %}","{% static 'cyber/imagen/fondo3.jpg' %}", "{% static 'cyber/imagen/fondo4.jpg' %}"];

		$(function() {
  
    	setInterval(changeImage, 30000);
  
						});

		function changeImage() {
  
 
   					$('body').css("background-image", 'url(' + listaimg[index] + ')');
                  
   						index++;
                  
   						if(index == 3)
      					index = 0;
    
    
								}
    </script>
  <style type="text/css">
  	body {
  		background-image: url("{% static 'cyber/imagen/fondo1.jpg'%}");
  		background-size: cover;
  		background-repeat: no-repeat;
  		margin: 0;
  		height: 100vh;
  		background-attachment: fixed;
}
  </style>

</div>

</body>
</html>





</html>